### PR TITLE
Handle user perm updates

### PR DESCRIPTION
**Pull request by jayrbolton**
Also, don't throw a RuntimeError on non-handled events.

I added a unit test for the `set_user_perms` function that I added. This also needs an integration test. But as I started working on it, I decided it would be too much work and time for now.

* [x] I incremented the version in the `VERSION` file
* [x] I updated `CHANGELOG.md`
* [x] I added test coverage for any changes

### CODE REVIEW

**Comment by slebras** [comment]
Is the only issue here that the dashboard uses the shared_users field? 
Are the objects searchable through search_api by the new users as is? search_api uses auth to check access right? just want to make sure I understand

**Comment by slebras** [comment]
> Also, don't throw a RuntimeError on non-handled events.
> 
> I added a unit test for the `set_user_perms` function that I added. This also needs an integration test. But as I started working on it, I decided it would be too much work and time for now.
> 
> * [x]  I incremented the version in the `VERSION` file
> * [x]  I updated `CHANGELOG.md`
> * [x]  I added test coverage for any changes

Test seems okay, maybe a little circular. would be nice to have the integration test for it, but not urgent i don't think

**Comment by slebras** [comment]
lgtm

**Review by slebras — COMMENTED** [review]
lgtm

**Comment by jayrbolton** [comment]
Yeah I agree the tests are circular. It doesn't assert that the ES query actually does the correct thing. But it does assert a specific behavior that will break if we muck around with the code in the future, so it's some kind of baseline.

> Is the only issue here that the dashboard uses the shared_users field?

Yeah this was brought up by the dashboard, but also deserves a fix in general 

> Are the objects searchable through search_api by the new users as is?

Not sure what you mean by "as is", the dashboard was finding narratives shared with the user using the "shared_users" field which wasn't updating. So it depends on the query.

> search_api uses auth to check access right? just want to make sure I understand

The API does use auth. It will query the workspace to get the IDs the user can access. So querying by the "shared_users" field is not really necessary. Someone might update that in the dashboard frontend. But this is still an indexing fix we should have in general.

**Pull request merged**
