### PR TITLE
Refactor AMAs

### PR DESCRIPTION
**Pull request by slebras**
* [x] I incremented the version in the `VERSION` file
* [x] I updated `CHANGELOG.md`
* [ ] I added test coverage for any changes

### CODE REVIEW

**Comment by scanon** [comment]
@jayrbolton Can you take a look at this?

**Comment by jayrbolton** [comment]
I was assuming this was incomplete as I don't see anywhere that "ama_config.yaml" is used (eg. how do the type mappings get initialized from that config?)

**Comment by jayrbolton** [comment]
Oh, I get what you're doing -- you're going to set a different config file url for a separately running instance of the indexer

**Comment by jayrbolton** [comment]
Do you want an image release for this? In that case we need to update the version in `/VERSION`

**Comment by jayrbolton** [comment]
Also a changelog entry would be good

**Comment by jayrbolton** [comment]
Why do we need a separate config? Can't you whitelist AMAs and still use the main config? Really the config is just used for initializing all the mappings and aliases.

**Comment by scanon** [comment]
> Why do we need a separate config? Can't you whitelist AMAs and still use the main config? Really the config is just used for initializing all the mappings and aliases.

Discussed in slack but the motivation is we will have a different namespace prefix (e.g. amaprod) and we only want certain indexes to get created.  So just having a pared down config seems like the easiest option.

**Comment by scanon** [comment]
I found an issue.  @slebras Can you add in the global_mappings section too.  This seems to be required.

**Comment by slebras** [comment]
Should I add the AMA configurations back to the original configuration file? Don't have a good read on that

**Comment by scanon** [comment]
> @scanon Should I add the AMA configurations back to the original configuration file? Don't have a good read on that

No.  I was saying you need to add in the global_mapping section into the AMA config because otherwise the indexer will fail when it tries to fetch it here....

https://github.com/kbase/index_runner/blob/47c432822c0c461bdb683ccd42794892c6381912/src/index_runner/es_indexer.py#L23

**Comment by slebras** [comment]
gotcha, added in commit 4a6b66b

**Pull request merged**
